CREATE DATABASE school;

USE school;

CREATE TABLE students(
    noControl VARCHAR(8) NOT NULL,
    name VARCHAR(35) NOT NULL,
    lastname VARCHAR(55) NOT NULL,
    gender VARCHAR(12) NOT NULL,
    age TINYINT NOT NULL,
    semester TINYINT NOT NULL,
    career VARCHAR(70) NOT NULL,
    PRIMARY KEY(noControl)
);

DESCRIBE students;

/* QUERYS  (GET, POST, PUT, DELETE)*/
SELECT * FROM students;
SELECT * FROM students WHERE noControl = ?;
UPDATE students SET name = ?, lastname = ?, gender = ?, age = ?, semester = ?, career = ? WHERE noControl = ?;
DELETE FROM students WHERE noControl = ?;

/* PROCEDURES */
DELIMITER //
CREATE PROCEDURE update_student(
    IN _noControl VARCHAR(8), 
    IN _name VARCHAR(35), 
    IN _lastname VARCHAR(55), 
    IN _gender VARCHAR(12), 
    IN _age TINYINT, 
    IN _semester TINYINT, 
    IN _career VARCHAR(70)
)
BEGIN
    DECLARE value INT;
    SELECT COUNT(noControl) INTO value FROM students WHERE noControl = _noControl;

    IF value<>0 THEN
        UPDATE students SET name = _name, lastname = _lastname, gender = _gender, age = _age, semester = _semester, career = _career WHERE noControl = _noControl;
    ELSE 
        SELECT 0;
    END IF;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE create_student(
    IN _noControl VARCHAR(8), 
    IN _name VARCHAR(35), 
    IN _lastname VARCHAR(55), 
    IN _gender VARCHAR(12), 
    IN _age TINYINT, 
    IN _semester TINYINT, 
    IN _career VARCHAR(70)
)
BEGIN
    DECLARE value INT;
    SELECT COUNT(noControl) INTO value FROM students WHERE noControl = _noControl;

    IF value<>0 THEN
        SELECT 0;
    ELSE 
        INSERT INTO students VALUES(_noControl,_name,_lastname,_gender,_age,_semester,_career);
    END IF;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE delete_student(
    IN _noControl VARCHAR(8)
)
BEGIN
    DECLARE value INT;
    SELECT COUNT(noControl) INTO value FROM students WHERE noControl = _noControl;

    IF value<>0 THEN
        DELETE FROM students WHERE noControl = _noControl;
    ELSE 
        SELECT 0;
    END IF;
END //
DELIMITER ;

CALL update_student('172T0000','BRIAM1','FLORES TORRES1','MASCULINE',18,1,'INGENIERIA EN SISTEMAS COMPUTACIONALES');
CALL create_student('172T0000','BRIAMs','FLORES','MASCULINE',18,1,'INGENIERIA EN SISTEMAS COMPUTACIONALES');

/* DATA EXAMPLE*/

INSERT INTO students values("172T0389","JUAN MANUEL","ALEJO GERÓN", "MASCULINO",21,"8","ING. SISTEMAS COMPUTACIONALES"),
("172T0391","KEILA","BARRANCO ROSAS","FEMENINO",25,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0393","EDGAR EDUARDO","CRUZ FERNANDO","MASCULINO",21,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0395","ALONDRA","FIGUEROA MALDONADO","FEMENINO",20,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0396","BRIAM","FLORES TORRES","MASCULINO",22,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0397","ELIEL ADAIR","GARCÍA BADILLO","MASCULINO",29,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0402","MAYRA LIZETH","GARCÍA TORRES","FEMENINO",23,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0405","EDUARDO","HERNÁNDEZ CASTELLANOS","MASCULINO",26,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0407","ALBA LIZETH","HERNÁNDEZ TRINIDAD","FEMENINO",27,8,"ING. SISTEMAS COMPUTACIONALES"),	
("172T0408","MARÍA DEL PILAR","HERNÁNDEZ ZARAZCA","FEMENINO",24,8,"ING. SISTEMAS COMPUTACIONALES"),	 	
("172T0409","GUSTAVO ADOLFO","LÓPEZ JIMÉNEZ","MASCULINO",22,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0412","SAÚL","LOYO RAMÍREZ","MASCULINO",29,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0414","CARLOS ALBERTO","MÉNDEZ BARRAGÁN","MASCULINO",25,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0416","KEVIN ISRAEL","MOTA LOZANO","MASCULINO",22,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0420","HIPOLITO","RONQUILLO HERNÁNDEZ","MASCULINO",20,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0422","LUIS FERNANDO","TIRADO HERNÁNDEZ","MASCULINO",21,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0423","JOSE DANIEL","VALLADARES MIRANDA","MASCULINO",25,8,"ING. SISTEMAS COMPUTACIONALES"),
("172T0424","OSCAR MIGUEL","VARGAS CONTRERAS","MASCULINO",20,8,"ING. SISTEMAS COMPUTACIONALES");